export const darkDreams = {
  id: 'dark_dreams',
  name: 'Dark Dreams',
  colors: {
    background: '#0a0a1a',
    foreground: '#e8e3ff',
    text: '#d1c7f0',
    primary: '#8b5cf6',
    'primary-foreground': '#f3f0ff',
    secondary: '#1e1b3a',
    'secondary-foreground': '#e8e3ff',
    accent: '#f472b6',
    'accent-foreground': '#0a0a1a',
    border: '#2a2a3e',
    input: '#1a1a2e',
    ring: '#8b5cf6',
    success: '#10b981',
    'success-foreground': '#0a0a1a',
    danger: '#ef4444',
    'danger-foreground': '#e8e3ff',
    warning: '#f59e0b',
    'warning-foreground': '#0a0a1a',
    muted: '#6b7280',
    'muted-foreground': '#9ca3af',
    card: '#0f0f1f',
    'card-foreground': '#e8e3ff',
    popover: '#0f0f1f',
    'popover-foreground': '#e8e3ff',
    destructive: '#ef4444',
    'destructive-foreground': '#e8e3ff',
  },
};
