export const highContrast = {
  id: 'high_contrast',
  name: 'High Contrast Dark',
  colors: {
    background: '#000000',
    foreground: '#ffffff',
    text: '#ffffff',
    primary: '#00aaff',
    'primary-foreground': '#000000',
    secondary: '#1a1a1a',
    'secondary-foreground': '#ffffff',
    accent: '#00ff88',
    'accent-foreground': '#000000',
    border: '#444444',
    input: '#1a1a1a',
    ring: '#00aaff',
    success: '#00ff00',
    'success-foreground': '#000000',
    danger: '#ff0044',
    'danger-foreground': '#ffffff',
    warning: '#ffaa00',
    'warning-foreground': '#000000',
    muted: '#888888',
    'muted-foreground': '#cccccc',
    card: '#111111',
    'card-foreground': '#ffffff',
    popover: '#111111',
    'popover-foreground': '#ffffff',
    destructive: '#ff0044',
    'destructive-foreground': '#ffffff',
  },
};
