export const modernLight = {
  id: 'modern_light',
  name: 'Modern Light',
  colors: {
    background: '#ffffff',
    foreground: '#0f172a',
    text: '#1e293b',
    primary: '#3b82f6',
    'primary-foreground': '#f8fafc',
    secondary: '#f1f5f9',
    'secondary-foreground': '#0f172a',
    accent: '#10b981',
    'accent-foreground': '#f0fdf4',
    border: '#e2e8f0',
    input: '#ffffff',
    ring: '#3b82f6',
    success: '#10b981',
    'success-foreground': '#f0fdf4',
    danger: '#ef4444',
    'danger-foreground': '#fef2f2',
    warning: '#f59e0b',
    'warning-foreground': '#fffbeb',
    muted: '#64748b',
    'muted-foreground': '#64748b',
    card: '#ffffff',
    'card-foreground': '#0f172a',
    popover: '#ffffff',
    'popover-foreground': '#0f172a',
    destructive: '#ef4444',
    'destructive-foreground': '#fef2f2',
  },
};
