export const modernDark = {
  id: 'modern_dark',
  name: 'Modern Dark',
  colors: {
    background: '#0a0a0a',
    foreground: '#fafafa',
    text: '#e4e4e7',
    primary: '#3b82f6',
    'primary-foreground': '#f8fafc',
    secondary: '#27272a',
    'secondary-foreground': '#fafafa',
    accent: '#10b981',
    'accent-foreground': '#0a0a0a',
    border: '#27272a',
    input: '#18181b',
    ring: '#3b82f6',
    success: '#10b981',
    'success-foreground': '#0a0a0a',
    danger: '#ef4444',
    'danger-foreground': '#fafafa',
    warning: '#f59e0b',
    'warning-foreground': '#0a0a0a',
    muted: '#71717a',
    'muted-foreground': '#a1a1aa',
    card: '#0f0f0f',
    'card-foreground': '#fafafa',
    popover: '#0f0f0f',
    'popover-foreground': '#fafafa',
    destructive: '#ef4444',
    'destructive-foreground': '#fafafa',
  },
};
