import { useState, useRef } from "react";
import { useGenerationStore } from "@/stores/useGenerationStore";
import { useUIStore } from "@/stores/useUIStore";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { Loader2, Image as ImageIcon, Edit, UploadCloud } from "lucide-react";
import { metadataService } from "@/services/metadataService";
import { toast } from "sonner";

export function MainCanvas() {
  const { currentImage, isGenerating, progress, currentStep, totalSteps } = useGenerationStore();
  const { setEditingImage } = useUIStore();
  const [isDragging, setIsDragging] = useState(false);
  const dragCounter = useRef(0);

  const handleDragEnter = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounter.current += 1;
    if (e.dataTransfer.items && e.dataTransfer.items.length > 0) {
      setIsDragging(true);
    }
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    dragCounter.current -= 1;
    if (dragCounter.current === 0) {
      setIsDragging(false);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
    dragCounter.current = 0;

    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const file = e.dataTransfer.files[0];
      if (file.type === "image/png") {
        const toastId = toast.loading("Reading metadata...");
        const params = await metadataService.parseImageFile(file);
        
        if (params) {
            const applied = metadataService.applyMetadata(params);
            if (applied) {
                toast.success("Parameters loaded from image", { id: toastId });
            } else {
                toast.warning("No compatible parameters found in image", { id: toastId });
            }
        } else {
            toast.error("Failed to read SwarmUI metadata", { id: toastId });
        }
      } else {
          toast.error("Please drop a PNG image generated by SwarmUI");
      }
    }
  };

  return (
    <div 
        className="h-full w-full bg-background relative flex flex-col overflow-hidden"
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
    >
      {/* Canvas Area */}
      <div className="flex-1 flex items-center justify-center relative p-6 bg-secondary/10">
        <div className="absolute inset-0 bg-[radial-gradient(#27272a_1px,transparent_1px)] bg-size-[16px_16px] mask-[radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)] pointer-events-none"></div>
        
        {/* Drag Overlay */}
        {isDragging && (
            <div className="absolute inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-center justify-center border-2 border-dashed border-primary m-4 rounded-xl animate-in fade-in duration-200">
                <div className="text-center space-y-2 pointer-events-none">
                    <div className="bg-primary/10 p-4 rounded-full inline-block">
                        <UploadCloud className="w-12 h-12 text-primary" />
                    </div>
                    <h3 className="text-2xl font-bold">Drop Image to Load Parameters</h3>
                    <p className="text-muted-foreground">Release to restore generation settings</p>
                </div>
            </div>
        )}

        {currentImage ? (
          <div className="relative max-w-full max-h-full shadow-2xl rounded-lg overflow-hidden border border-border group">
            <img 
              src={currentImage} 
              alt="Generated Content" 
              className="max-w-full max-h-full object-contain"
            />
            
            {/* Overlay Actions */}
            {!isGenerating && (
                <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity">
                    <Button 
                        size="sm" 
                        variant="secondary" 
                        className="shadow-lg backdrop-blur-md bg-background/80"
                        onClick={() => setEditingImage(currentImage)}
                    >
                        <Edit className="w-4 h-4 me-2" />
                        Edit / Inpaint
                    </Button>
                </div>
            )}
          </div>
        ) : (
          <div className="relative z-10 text-center space-y-4 text-muted-foreground/50">
            <div className="flex justify-center">
                <ImageIcon className="w-24 h-24 opacity-20" />
            </div>
            <div>
                <h1 className="text-4xl font-bold tracking-tight text-foreground/20">ReactiveSwarm</h1>
                <p>Ready to generate.</p>
            </div>
          </div>
        )}
      </div>

      {/* Progress Overlay / Footer */}
      {(isGenerating || progress > 0) && (
        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 w-full max-w-md bg-popover/80 backdrop-blur-md border border-border p-4 rounded-xl shadow-lg z-50 transition-all duration-300">
            <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                    {isGenerating && <Loader2 className="w-4 h-4 animate-spin text-primary" />}
                    <span className="text-sm font-medium">
                        {isGenerating ? "Generating..." : "Ready"}
                    </span>
                </div>
                <span className="text-xs text-muted-foreground">
                    {currentStep} / {totalSteps} steps ({Math.round(progress * 100)}%)
                </span>
            </div>
            <Progress value={progress * 100} className="h-2" />
        </div>
      )}
    </div>
  );
}
